import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import ConvexClientProvider from "./components/providers/ConvexClienProvider";
import Footer from "./components/Footer/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Clerk Next.js Quickstart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable}
          antialiased min-h-screen bg-linear-to-b from-gray-900 to-gray-950
          text-gray-100 flex flex-col`}
        >
          <div>
            <ConvexClientProvider>
              {children}
            </ConvexClientProvider>
          </div>
          <Footer />
        </body>
      </html>
    </ClerkProvider>
  );
}
